mode: 'full'
training:
  CUDA_DEVICE_ORDER: 'PCI_BUS_ID'
  epochs: 50
  batch_size: 4
  num_workers: 4
  train_size: 'all'
model:
  arch: 'ConvNeXtV2_3D'
  img_size: [128,128,128]
  in_chans: 1
  n_classes: None
  drop_path_rate: 0.1
  depths: [3, 3, 9, 3]
  dims: [32, 64, 128, 256]
  kernel_size: 7
  padding: 3
  downsampling: 'avgpool3d'
solver:
  optimizer: 'AdamW'
  lr: 0.00001
  weight_decay: 0.01
  betas: [0.9, 0.999]
transforms:
  spacing: [1, 1, 1]
  resize: [128,128,128]
  orientation: "RAS"
  normalize_non_zero: True
  cache_dir_train: "./monai_cache/"
  cache_dir_test: "./monai_cache/"
ADNI1:
  dataroot: "./data/uda/data/ADNI1_preprocessed_arranged/"
  labelsroot: "./data/uda/data/ADNI1_11_24_2025.csv"
  mode: 'training'
ADNI2:
  dataroot: "./data/uda/data/ADNI2/"
  labelsroot: "./data/uda/data/ADNI2_11_24_2025.csv"
  mode: 'training'
AIBL:
  dataroot: "./data/uda/data/AIBL/"
  labelsroot: "./data/uda/data/AIBL_CNAD_Baseline_MRI.csv"
  mode: 'training'