TRAINING:
  CUDA_DEVICE_ORDER: 'PCI_BUS_ID'
  USE_GPU: True
  EPOCHS: 600
  CHECKPOINT: './checkpoints/'
  LOGGING_PERIOD: 200
  LOGGING_PATH: './logs/'
  EARLY_STOPPING: False
  EARLY_STOPPING_DELTA: 0.00001
  EARLY_STOPPING_PATIENCE: 5
  CHECKPOINT_TYPE: None

TESTING:
  USE_GPU: True

MODEL:
  TYPE: 'FCMAE_3D'
  img_size: [128,128,128]
  in_chans: 1
  n_classes: None
  drop_path_rate: 0.1
  depths: [3, 3, 27, 3]
  dims: [64, 128, 256, 512]
  kernel_size: 7
  padding: 3
  downsampling: avgpool3d
  decoder_depth: 1
  decoder_embed_dim: 768
  patch_size: 32
  mask_ratio: 0.6
  norm_pix_loss: False
  encoder_type: sparse_convnextv2


IXI:
  dataroot: "./data/IXI-T1/hdbet/IXI*/*T1.nii.gz"

HCP:
  dataroot: "./data/HCP/hdbet/*/hdbet_n4*1.nii.gz"

DATALOADER:
  BATCH_SIZE: 4
  NUM_WORKERS: 8

SOLVER:
  optimizer: 'AdamW'
  lr: 0.0001
  weight_decay: 0.0001
  warmup_epochs: 40
  min_lr: 0.0000001
  beta1: 0.9
  beta2: 0.95

TRANSFORMS:
  spacing: [1.75, 1.75, 1.75]
  resize: [128, 128, 128]
  normalize_non_zero: True
  orientation: "RAS"
  cache_dir_train: None
  cache_dir_test: None
