training:
  epochs: 600
  warmup_epochs: 40
  checkpoints: './checkpoints/'
  batch_size: 16
  num_workers: 8
  use_fp16: True
  saveckp_freq: 50
model:
  arch: 'FCMAE_3D'
  img_size: [128,128,128]
  in_chans: 1
  depths: [3, 3, 27, 3]
  dims: [64, 128, 256, 512]
  kernel_size: 7
  padding: 3
  downsampling: avgpool3d
  decoder_depth: 1
  decoder_embed_dim: 768
  patch_size: 32
  mask_ratio: 0.6
  norm_pix_loss: False
  encoder_type: convnextv2
  # drop_path_rate: 0.1
optimizer:
  optimizer: 'adamw'
  lr: 0.005
  weight_decay: 0.005
  min_lr: 0.0000001
  beta1: 0.9
  beta2: 0.95
  clip_grad: 3
transforms:
  spacing: [1, 1, 1]
  resize: [128, 128, 128]
  normalize_non_zero: True
  orientation: "RAS"
  cache_dir_train: None
  cache_dir_test: None
IXI:
  dataroot: "./data/IXI-T1/hdbet/IXI*/*T1.nii.gz"
HCP:
  dataroot: "./data/HCP/hdbet/*/hdbet_n4*1.nii.gz"